### ISSUE TITLE
v4 support?

### ISSUE THREAD

**Issue by Stumblinbear** [deepstreamIO/deepstream.io-client-java#141]
When will support be coming for v4 in this client?

**Comment by xukaifu** [comment]
We also need it.

**Comment by yasserf** [comment]
V4 is fundamentally different to V3 in how the clients are written. This was done intentionally since the initial text protocol was a bit of a pain to work with. There is an effort to create a V3 compatibility layer, however this will not take advantage of alot of the new protocol features. Writing an SDK takes a very long time, and I don't want to run into it similar to the current Java one, but rather take an approach that will be easy to maintain going forward.

The V3 compat layer is a WIP currently, not sure what the ETA is.

**Comment by Stumblinbear** [comment]
As a quick request on the side, if you could, in the update, include a way to decode and encode objects using your own Gson object, that would be fabulous. Currently I have it encode it and decode it as JsonElement, then encode/decode that after the fact, however it seems hacky.

**Comment by yasserf** [comment]
okay so update, there will be a 4.1 release soon that has a V3 endpoint allowing people to use the text-based protocol. Unfortunately you can't use both V4 and V3 at the same time (unless you use clustering for now). But it still means you can migrate the server easily.

In regards to the Java SDK I'm a little torn. Generally I want to remove all concepts of it having a json library and instead just use strings (serialized json). The only thing we will lose is patches which isn't the end of the world in comparison to how much simpler the SDK will be. However I don't have the time to do any SDK stuff yet =(

**Comment by yasserf** [comment]
Update, the compat layer is complete and supports both V4 and V3! If your interested I can release an RC, let me know

**Comment by yasserf** [comment]
Released 4.1 which supports both V3 and V4 clients simultaneously at a small CPU expense. Let me know how it goes!
