### ISSUE TITLE
RPC makeAsync.

### ISSUE THREAD

**Issue by chinmaygit** [deepstreamIO/deepstream.io-client-java#65]
RPC's sometime take longer time to execute, making rpc's async solves this issue.

**Comment by yasserf** [comment]
RPCs (and everything) are async under the hood, the API is sync because you should be handling it in your own thread that reacts accordingly.

We could have a makeAsync api that just exposes the callback mechanism instead if you want to avoid doing that due to complexity or cost of creating, but we would need to be consistent and do it for has/snapshot/etc
