### ISSUE TITLE
Client data not coming through in LoginResult.getData()

### ISSUE THREAD

**Issue by AlexBHarley** [deepstreamIO/deepstream.io-client-java#71]
I get the clientData successfully on javascript. But now when I try to get it on Android, it's coming emptry. Shouldn't `LoginResult.getData()` work?

**Comment by atumn** [comment]
Turns out my client version was outdated.

[this block](https://github.com/deepstreamIO/deepstream.io-client-java/blob/43f8c5d08f2c236c97ae7bd38753001b25fa48e3/src/main/java/io/deepstream/Connection.java#L309-L316)
`if( this.loginCallback != null ) {
                try {
                    Object data = MessageParser.convertTyped(message.data[0], this.client);
                    this.loginCallback.loginSuccess(data);
                } catch (IndexOutOfBoundsException e) {
                    this.loginCallback.loginSuccess(null);
                }
            }`
was like this:
`            if(this.loginCallback != null) {
                this.loginCallback.loginSuccess(new HashMap());
            }`
in my version. You can close this issue.

**Comment by AlexBHarley** [comment]
Thanks for getting back to us!
