### ISSUE TITLE
[Question] Offline Capabilities

### ISSUE THREAD

**Issue by matecode** [deepstreamIO/deepstream.io-client-java#97]
Hi! 

For many reasons i cant and wont use firebase. Therefore I try to figure out what i can do with deepstream. Now I'm researching offline capabilities. As you can imagine I have some questions:

Is there some kind of built in cache or local storage?

What happens to messages send while reconnecting or offline 

Thanks for your help.

**Comment by yasserf** [comment]
> Is there some kind of built in cache or local storage?

Currently no, we are looking into providing offline functionality as a hook so you can save your documents locally, but we haven't finalised it yet.

> What happens to messages send while reconnecting or offline

Updates get cached and sent down whenever a reconnect occurs. The server validates the message was correct by comparing the version number it receives against the version number it has in its datastore and if it isn't a natural progression (current version + 1) it notifies the client so that it can resolve the conflict client side

**Comment by yasserf** [comment]
Hope that answers your question, feel free to reopen if you have any followup!
